### ISSUE TITLE
common larceny from network share has early death

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#531]
**Reported by: pnkfelix  on Sat Feb 23 14:20:41 2008**
If you attempt to run Common Larceny from a network shared drive in Windows, you get the following error before the runtime gets the chance to spit out any output of its own:

```
Z:\nemeanlion\larcenydev\trunk-dotnet\larceny_src>dotnet.heap.exe
...
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Scheme.RT.Load' threw an exception. ---> System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.EnvironmentPermission, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.Environment.GetEnvironmentVariable(String variable)
   at Scheme.RT.Load..cctor()
```

This is because by default, .NET applications only have unrestricted access to things like environment variables if you run them from the local hard drive.

I believe we could document a work around for the bug (e.g. "give common larceny better permissions"), but I suspect we might be able to do better than that, like catch the exception ourselves and ask the user how they would like us to proceed.  

We do not need to get at many environment variables, and some can be chosen by command line switches instead.  So we may be able to put in a real simple stopgap solution of telling the user to supply the appropriate options and then exiting.

All I know is that stack traces are scary.

**Comment by icefoxen** [comment]
This may have gotten simplified .NET version 4.0, see https://blogs.msdn.microsoft.com/shawnfa/2009/05/22/sandboxing-in-net-4-0/
